### ISSUE TITLE
only_fj not working properyl

### ISSUE THREAD

**Issue by benjaminvatterj** [JuliaNLSolvers/NLsolve.jl#166] opened 2018-04-28 18:44 UTC
The option of providing a single function that computes both residual and jacobian doesnt seem to work as expected. Here the same example as the one from the documentation:

```
using NLsolve

function myfun!(F, J, x)
       if !(F == nothing)
           F[1] = (x[1]+3)*(x[2]^3-7)+18
           F[2] = sin(x[2]*exp(x[1])-1)
       end

       if !(J == nothing)
           J[1, 1] = x[2]^3-7
           J[1, 2] = 3*x[2]^2*(x[1]+3)
           u = exp(x[1])*cos(x[2]*exp(x[1])-1)
           J[2, 1] = x[2]*u
           J[2, 2] = u
       end
end
```

Now to use it
```

nlsolve(only_fj!(myfun!), [0.5, 0.5])
ERROR: UndefVarError: only_fj! not defined
```

Maybe its not exported

```
nlsolve(NLsolve.only_fj!(myfun!), [0.5, 0.5])
ERROR: MethodError: objects of type NLSolversBase.InplaceObjective{Void,#myfun!,Void} are not callable

nlsolve(NLsolve.only_fj(myfun!), [0.5, 0.5])
ERROR: MethodError: objects of type NLSolversBase.NotInplaceObjective{Void,#myfun!,Void} are not callable
```

an obvious work around is 
```
f!(F,x) = myfun!(F, nothing, x)
j!(J,x) = myfun!(nothing, J, x)
 df = OnceDifferentiable(f!, j!, myfun!, initial_x, initial_F)
nlsolve(df, intial_x)

```

**Comment by pkofod** [comment] 2018-04-28 18:48
What’s your pkg.status? I think this is fixed on nlsolversbase master . Sorry for the inconvenience

**Comment by benjaminvatterj** [comment] 2018-04-28 19:07
Is this what you are referring to?
```
julia> Pkg.status("NLsolve")
 - NLsolve                       1.0.1
```

**Comment by pkofod** [comment] 2018-04-28 19:35
That and `Pkg.status("NLSolversBase")`, yes.

**Comment by pkofod** [comment] 2018-04-28 19:58
Alright, the problem is that there's no method of `nlsolve` that handles the type constructed by `only_fj!` (and that NLsolve doesn't rexport `only_fj!`).

```
julia> od = OnceDifferentiable(NLSolversBase.only_fj!(myfun!), zeros(2), zeros(2))
NLSolversBase.OnceDifferentiable{Array{Float64,1},Array{Float64,2},Array{Float64,1},Val{false}}(NLSolversBase.#12, NLSolversBase.#14, myfun!, [0.0, 0.0], [NaN NaN; NaN NaN], [NaN, NaN], [NaN, NaN], [0], [0])

julia> nlsolve(od, [0.5, 0.5])
Results of Nonlinear Solver Algorithm
 * Algorithm: Trust-region with dogleg and autoscaling
 * Starting Point: [0.5, 0.5]
 * Zero: [-3.93704e-14, 1.0]
 * Inf-norm of residuals: 0.000000
 * Iterations: 5
 * Convergence: true
   * |x - x'| < 0.0e+00: false
   * |f(x)| < 1.0e-08: true
 * Function Calls (f): 6
 * Jacobian Calls (df/dx): 6
```

**Comment by pkofod** [comment] 2018-04-28 20:01
(thanks for a great bug report btw)

**Comment by pkofod** [comment] 2018-04-28 20:25
let me make and merge the pull request, then I'll close it :)

**Closed** 2018-04-28 20:59 UTC

**Comment by pkofod** [comment] 2018-04-28 21:06
When https://github.com/JuliaLang/METADATA.jl/pull/14435 is merged, the fix will be applied by doing a `Pkg.update()`

**Comment by pkofod** [comment] 2018-04-30 07:15
you can `Pkg.update()` now @benjaminvatterj

**Comment by benjaminvatterj** [comment] 2018-04-30 12:08
Great! thanks for the quick fix!
